// Package querypresets : set the Querys in advance
package querypresets

import "gitee.com/cai-zixiang_hainan/wt/internal/model"

var ClientHostPortQuery = model.Query{
	Head:    ">>set the server -> host:port<<",
	Example: "192.168.1.2:12212",
	Default: "192.168.1.2:12212",
}

var ClientReadTimeoutQuery = model.Query{
	Head:    ">>set the read time out for client<<",
	Example: "20s",
	Default: "20s",
}

var ClientInstallTimeoutQuery = model.Query{
	Head:    ">>set the install timeout for client<<",
	Example: "3h",
	Default: "3h",
}

var ClientWriteTimeoutQuery = model.Query{
	Head:    ">>set the write timeout for client<<",
	Example: "3h",
	Default: "3h",
}

var ClientReadTokenQuery = model.Query{
	Head:    ">>set the read token for client<<",
	Example: "xxxxxxx",
	Default: "generated by random",
}

var ClientInstallTokenQuery = model.Query{
	Head:    ">>set the install token for client<<",
	Example: "xxxxxxx",
	Default: "generated by random",
}

var ClientWriteTokenQuery = model.Query{
	Head:    ">>set the write token for client<<",
	Example: "xxxxxxx",
	Default: "generated by random",
}
